name: cpp-linter as action

on:
  workflow_dispatch:
  workflow_call:
  pull_request:


jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        clang-version: ['9','10', '11', '12', '13', '14', '15', '16', '17', '18']
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          repository: cpp-linter/test-cpp-linter-action

      - name: Cache the build artifacts
        id: cache-build
        uses: actions/cache@v4
        with:
          path: build
          key: ${{ runner.os }}-${{ hashFiles('src/CMakeLists.txt', 'src/demo.cpp', 'src/demo.hpp') }}

      - name: Generate compilation database
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: mkdir build && cmake -Bbuild src

      - name: Run linter as action
        uses: cpp-linter/cpp-linter-action@opt-in-color
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CPP_LINTER_COLOR: true
        with:
          style: file
          files-changed-only: false
          # to ignore all build folder contents
          ignore: build
          database: build
          verbosity: debug
          version: ${{ matrix.clang-version }}
          thread-comments: ${{ matrix.clang-version == '16' && 'update' }}
          file-annotations: ${{ matrix.clang-version == '16' && 'update' }}
          extra-args: -std=c++14 -Wall

      - name: Fail fast?!
        # if: steps.linter.outputs.checks-failed > 0
        run: | 
          echo "some linter checks failed"
          echo "${{ steps.linter.outputs.checks-failed }}"
        # for actual deployment
        # run: exit 1
